### ISSUE TITLE
Calimero 2.5?

### ISSUE THREAD

**Issue by frankvandenhurk** [scantineau/knx2mqtt#4]
Thank you for your effort to upgrade to Calimero 2.4. Unfortunately, there are still some DPTs that are used in my project and are included in Calimero 2.5 and not in 2.4.

Tried to upgrade to 2.5 myself, but no luck (I im not a programmer). This is what I did:

Changed the build image, since Calimero 2.5 needs Java11:

```
-FROM mrfroop/openjdk-alpine-gradle AS BUILD_IMAGE
+FROM gradle:6.9.2-jdk11-alpine AS BUILD_IMAGE
```

Changed the build.gradle file:

```
-sourceCompatibility = 1.8
-targetCompatibility = 1.8
+sourceCompatibility = 11
+targetCompatibility = 11
```

```
-    compile 'com.github.calimero:calimero-core:2.4'
+    compile 'com.github.calimero:calimero-core:2.5'
```

Unfortunately, it llooks like that 2.5 is not coompletely backwards compatible (or I did something wrong):

```
> Task :compileJava
/app/src/main/java/com/tellerulam/knx2mqtt/knx/KNXConnector.java:135: warning: [removal] TP1 in TPSettings has been deprecated and marked for removal
        link = KNXNetworkLinkIP.newTunnelingLink(local, new InetSocketAddress(hostIP, port), nat, TPSettings.TP1);
                                                                                                            ^
/app/src/main/java/com/tellerulam/knx2mqtt/knx/KNXConnector.java:201: error: cannot find symbol
                        val = ProcessListener.asUnsigned(pe, ProcessCommunicationBase.UNSCALED);
                                                             ^
  symbol:   variable ProcessCommunicationBase
  location: class KNXConnector.MyProcessListener
1 error
1 warning
```

Any ideas?

**Comment by scantineau** [comment]
Hello ! 
I almost completely refactored the code to implement multiple mqtt handlers but I think custom handlers are not a good practice (with custom paths such as /knx/something/command) so I decided to implement the Home Assistant one (status : testing at home) and I'm working on the Homie standard which is a bit more complicated to implement.
Maybe I could tag and release a new image for you if you want but I did not updated the documentation yet.

**Comment by frankvandenhurk** [comment]
Sure, happy to test

**Comment by scantineau** [comment]
Please try this new image : scantineau/knx2mqtt:1.0.0-alpha1
I replaced the properties with a config file, which is much easier to configure.

Here is an example of the config file knx2mqtt.yml : 
```
mqtt:
  server: "tcp://192.168.x.y:1883"
  user: mosquitto #optional
  password: somePassword #optional
  clientid: knx2mqtt #optional
knx:
  type: TUNNELING
  ip: 192.168.x.y
#localip : you can choose to bind an ip address or an interface. So that way you can have a dynamic ip or use this image on a swarm (if all servers have the same interface)
  #  localip: 192.168.x.y
  localip: enp3s0/4 
  nat: true
homeassistant:
  devices:
    - name: bureau_test_switch
      deviceType: switch
      functions:
        - type: command
          ga: 1/1/1
          dpt: 1.001
        - type: state
          ga: 1/4/1
          dpt: 1.001
    - name: bureau_test_light
      deviceType: light
      functions:
        - type: command
          ga: 1/1/1
          dpt: 1.001
        - type: state
          ga: 1/4/1
          dpt: 1.001
        - type: brightness_command
          ga: 1/3/1
          dpt: 5.001
        - type: brightness_state
          ga: 1/3/1
          dpt: 5.001
    - name: porte_garage
      deviceType: switch
      functions:
        - type: command
          ga: 5/1/0
          dpt: 1.010
        - type: state
          ga: 5/2/0
          dpt: 1.001
```

And a docker-compose.yml example : 
```
version: '3'
services:
  knx2mqtt:
    image: scantineau/knx2mqtt:1.0.0-alpha1
    environment:
      - KNX2MQTT_CONFIG_FILE_PATH=/knx2mqtt.yml
    volumes:
      - "$(pwd)/knx2mqtt.yml:/knx2mqtt.yml"
```

Since it's a way to bind to a standard (home assistant and homie in a next version), there are some translation from official DPT for home assistant to understand the commands, and obviously translated from home assistant to DPT.

Here's a link to understand the home assistant configuration and topics : https://www.home-assistant.io/docs/mqtt/discovery/
